# Generated by Django 4.2.7 on 2023-11-25 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.CharField(max_length=320, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('category_type', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.CharField(max_length=320, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('producer', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'db_table': 'Product_Meta',
            },
        ),
        migrations.CreateModel(
            name='Product_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('in_stock', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.product')),
            ],
            options={
                'db_table': 'Product_Item',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.product_meta'),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.order')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.product_item')),
            ],
            options={
                'db_table': 'Order_Item',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('status', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.order')),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.product')),
            ],
            options={
                'db_table': 'Cart_Item',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.customer'),
        ),
    ]
